In [3]:
import pandas as pd 
import numpy as np

Criando a função para relatório inicial das bases

In [4]:
def relatorio_inicial(df):
    """
    PRE AVALIACAO DA BASE
    """
    print("=" * 48)
    print(f"ETAPA 1 - AUDITORIA")
    print("=" * 48)
    
    print("\n[0] COLUNAS DA BASE:")
    print(df.columns.tolist())
    
    print("\n[1] INFO DA BASE:")
    df.info()
    
    print("\n[2] TIPOS DE DADOS (dtypes):")
    print(df.dtypes)
    
    print("\n[3] ESTATÍSTICAS DESCRITIVAS (Numéricas):")
    print(df.describe())

    '''print("\n[4] ESTATÍSTICAS DESCRITIVAS (Objetos/Texto): ")
    try:
        print(df.describe(include='object'))
    except ValueError:
        print("Não há colunas de texto nesta base.")'''
    
    print("\n[5] QUANTIDADE DE NULOS POR COLUNA:")
    print(df.isnull().sum())
     
    print("\n[6] PERCENTUAL DE NULOS (> 15%):")
    percentual_nulos = (df.isnull().sum() / len(df) * 100).round(1)
    print(percentual_nulos)
        
    print("\n[7] LINHAS COM VALORES NULOS:")
    qtd_nulos_linhas = df.isnull().any(axis=1).sum()
    print(f"Total de linhas com pelo menos um valor nulo: {qtd_nulos_linhas}")
    
    print("\n[8] TOTAL DE LINHAS DUPLICADAS:")
    total_duplicadas = df.duplicated().sum()
    print(f"Total: {total_duplicadas}")
    
    print("\n" + "=" * 48)
    print(f"FIM DO RELATÓRIO")
    print("=" * 48 + "\n")

## Convertendo as bases em Dataframe

Concatenando base adicional de clientes à base original 2023-2024

In [5]:
canais = pd.read_csv('canais_venda.csv', sep=';', encoding='utf-8')
clientes = pd.read_csv('clientes.csv', sep=';', encoding='utf-8')
funcionarios = pd.read_csv('funcionarios.csv', sep=';', encoding='utf-8')
reservas = pd.read_csv('reservas.csv', sep=';', encoding='utf-8')
quartos = pd.read_csv('tipos_quarto.csv', sep=';', encoding='utf-8')
unidades = pd.read_csv('unidades.csv', sep=';', encoding='utf-8')

#Adicionando clientes novos às bases
clientes_novos=pd.read_csv('clientes_novos.csv', sep=';', encoding='utf-8')
df_concatenado_clientes = pd.concat([clientes, clientes_novos], ignore_index=True)

quartos_novos=pd.read_csv('tipos_quarto_novos.csv', sep=';', encoding='utf-8')
df_concatenado_quartos = pd.concat([quartos, quartos_novos], ignore_index=True)

funcionarios_novos=pd.read_csv('funcionarios_novos.csv', sep=';', encoding='utf-8')
df_concatenado_funcionarios = pd.concat([funcionarios, funcionarios_novos], ignore_index=True)

reservas_novos=pd.read_csv('reservas_novas.csv', sep=';', encoding='utf-8')
df_concatenado_reservas = pd.concat([reservas, reservas_novos], ignore_index=True)

## Etapa 1 - Auditoria

Aplica a função relatório inicial. Identifica inconsistências iniciais na base

In [17]:
#relatorio_inicial (canais)
#relatorio_inicial (clientes)
relatorio_inicial (funcionarios)
#relatorio_inicial(reservas)
#relatorio_inicial(quartos)
#relatorio_inicial(unidades)
#relatorio_inicial(clientes_novos)

================================================
ETAPA 1 - AUDITORIA
================================================

[0] COLUNAS DA BASE:
['id_funcionario', 'id_unidade', 'nome', 'cargo', 'departamento', 'salario', 'data_admissao']

[1] INFO DA BASE:
<class 'pandas.DataFrame'>
RangeIndex: 134 entries, 0 to 133
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   id_funcionario  134 non-null    int64
 1   id_unidade      134 non-null    int64
 2   nome            134 non-null    str
 3   cargo           134 non-null    str
 4   departamento    134 non-null    str
 5   salario         128 non-null    str
 6   data_admissao   134 non-null    str
dtypes: int64(2), str(5)
memory usage: 7.5 KB

[2] TIPOS DE DADOS (dtypes):
id_funcionario    int64
id_unidade        int64
nome                str
cargo               str
departamento        str
salario             str
data_admissao       str
dtype: object

[3] ESTATÍSTICAS DESCRITIVAS (Numéricas):
       id_funcionario  id_unidade
count      134.000000  134.000000
mean        67.500000    6.694030
std         38.826537    3.664969
min          1.000000    1.000000
25%         34.250000    4.000000
50%         67.500000    7.000000
75%        100.750000   10.000000
max        134.000000   12.000000

[5] QUANTIDADE DE NULOS POR COLUNA:
id_funcionario    0
id_unidade        0
nome              0
cargo             0
departamento      0
salario           6
data_admissao     0
dtype: int64

[6] PERCENTUAL DE NULOS (> 15%):
id_funcionario    0.0
id_unidade        0.0
nome              0.0
cargo             0.0
departamento      0.0
salario           4.5
data_admissao     0.0
dtype: float64

[7] LINHAS COM VALORES NULOS:
Total de linhas com pelo menos um valor nulo: 6

[8] TOTAL DE LINHAS DUPLICADAS:
Total: 0

================================================
FIM DO RELATÓRIO
================================================

## Limpeza e tratamento

### Base: funcionários

Atualização e Correção da Base Salarial com map

In [13]:
novos_salarios = {
    9: '1870.00',
    10:'2314.00',
    14: '5480.00',
    37: '2950.00',
    43:'5600.00',
    92:'8600.00',
    104:'2890.00',
    11:'2800.00',
    26:'2150.00',
}

df_concatenado_funcionarios.loc[df_concatenado_funcionarios['id_funcionario'].isin(novos_salarios), 'salario'] = df_concatenado_funcionarios['id_funcionario'].map(novos_salarios)

In [10]:
sorted(df_concatenado_funcionarios['cargo'].unique())

['ANALISTA FINANCEIRO',
 'AUXILIAR DE LIMPEZA',
 'Analista Financeiro',
 'Auxiliar de Limpeza',
 'CAMAREIRA',
 'COZINHEIRO',
 'Camareira',
 'Chef de Cozinha',
 'Concierge',
 'Cozinheiro',
 'Gerente',
 'MANUTENÇÃO',
 'Manobrista',
 'Manutenção',
 'Manutenção ',
 'RECEPCIONISTA',
 'Recepcionista',
 'Recepcionista ',
 'SEGURANÇA',
 'Segurança',
 'Sommelier',
 'analista financeiro',
 'camareira',
 'cozinheiro',
 'gerente',
 'recepcionista',
 'segurança']

In [11]:
df_concatenado_funcionarios['cargo'] = df_concatenado_funcionarios['cargo'].str.strip().str.title()

In [6]:
df_concatenado_funcionarios= df_concatenado_funcionarios.drop_duplicates(
     subset=['nome','departamento'],
     keep='first')

In [7]:
df_concatenado_funcionarios.head(50)

,id_funcionario,id_unidade,nome,cargo,departamento,salario,data_admissao
0,1,1,Gabriela Lima,Auxiliar de Limpeza,Governança,"""2.139,00""",2020-10-05
1,2,1,Abel Correia,Segurança,Segurança,"""1.746,00""",2021-12-29
2,3,1,Sara Teixeira,analista financeiro,Financeiro,"""5.356,00""",2022-03-01
3,4,1,Julia Monteiro,Auxiliar de Limpeza,Governança,"""2.070,00""",2019-06-10
4,5,1,Daniela Ramos,Auxiliar de Limpeza,Governança,"""1.572,00""",2018-10-16
5,6,1,Lucas Souza,Auxiliar de Limpeza,Governança,"""1.955,00""",2024-02-01
6,7,1,Wilson Duarte,Recepcionista,Recepção,"""1.906,00""",2023-03-24
7,8,1,Nicolas Cunha,Recepcionista,Recepção,"""2.417,00""",2019-07-02
8,9,1,Bruno Costa,Auxiliar de Limpeza,Governança,NaN,2021-11-02
9,10,1,Bruno Costa,Manutenção,Manutenção,"""2.314,00""",2022-11-28
10,11,1,Gabriela Lima,camareira,Gov.,"""-2800,00""",2020-12-11
11,12,1,Zara Moraes,Manutenção,Manutenção,"""1.880,00""",2022-05-21
12,13,1,Roberta Leite,Manutenção,Manutenção,"""1.882,00""",2023-11-15
13,14,1,Yuri Castro,Analista Financeiro,Financeiro,NaN,2022-12-31
14,15,1,Fernanda Cruz,Camareira,Governança,"""1.944,00""",2023-11-07
15,16,2,Nicolas Cunha,Cozinheiro,Alimentos e Bebidas,"""3.208,00""",2024-02-01
16,17,2,Ivan Azevedo,Manutenção,Manutenção,"""2.377,00""",2024-09-28
17,18,2,Larissa Sousa,Cozinheiro,Alimentos e Bebidas,"""2.647,00""",2024-01-21
18,19,2,Karen Alves,Manutenção,Manutenção,"""2.377,00""",2018-11-09
19,20,2,Yuri Castro,Segurança,Segurança,"""2.473,00""",2024-01-15
20,21,2,Diego Ferreira,Segurança,Segurança,"""1.800,00""",2018-03-29
21,22,2,Ximena Godoi,ANALISTA FINANCEIRO,Financeiro,"""5.534,00""",2019-06-02
22,23,2,Wesley Araujo,Cozinheiro,Alimentos e Bebidas,"""3.066,00""",2020-08-28
23,24,3,Paulo Ribeiro,MANUTENÇÃO,Manutenção,"""2.530,00""",2023-03-11
24,25,3,Ursula Pinto,ANALISTA FINANCEIRO,Financeiro,"""5.569,00""",2020-11-18
25,26,3,Gabriela Lima,MANUTENÇÃO,Manutenção,"""999.999,00""",2019-03-05
26,27,3,Gabriela Lima,ANALISTA FINANCEIRO,Financeiro,"""5.226,00""",2021-04-13
27,28,3,Ana Silva,Analista Financeiro,Financeiro,"""5.498,00""",2018-08-24
28,29,3,Kleber Pires,cozinheiro,Alimentos e Bebidas,"""3.033,00""",2021-07-17
29,30,3,Fernanda Cruz,MANUTENÇÃO,Manutenção,"""1.949,00""",2019-06-28
30,31,3,Xuxa Farias,Camareira,Governança,"""1.757,00""",2022-09-23
32,33,4,Victor Gomes,Auxiliar de Limpeza,Governança,"""1.840,00""",2023-05-24
33,34,4,Ursula Pinto,Manutenção,Manutenção,"""2.417,00""",2020-06-14
34,35,4,Sara Teixeira,Segurança,Segurança,"""2.452,00""",2022-03-15
37,38,4,Carlos Neto,Cozinheiro,A&B,"""2.798,00""",2020-05-01
38,39,4,Isabela Martins,Auxiliar de Limpeza,Governança,"""2.048,00""",2020-03-04
39,40,4,Elena Santos,Analista Financeiro,Financeiro,"""5.659,00""",2019-03-28
40,41,4,Ivan Azevedo,Analista Financeiro,Financeiro,"""5.237,00""",2018-11-24
42,43,4,Wilson Duarte,Analista Financeiro,Financeiro,NaN,2022-01-07
43,44,4,Gustavo Vieira,Cozinheiro,Alimentos e Bebidas,"""3.264,00""",2019-12-03
44,45,4,Zara Moraes,Segurança,Segurança,"""2.174,00""",2021-01-19
46,47,5,Thiago Matos,Segurança,Segurança,"""2.051,00""",2019-07-31
47,48,5,Carlos Neto,Camareira,Governança,"""2.239,00""",2023-08-18
48,49,5,Victor Gomes,RECEPCIONISTA,Recepção,"""2.563,00""",2022-03-08
49,50,5,Julia Monteiro,Gerente,Administração,"""8.363,00""",2020-05-17
50,51,5,Lucas Souza,Gerente,Administração,"""8.855,00""",2022-09-15
51,52,5,Larissa Sousa,Auxiliar de Limpeza,Governança,"""1.839,00""",2024-03-20
52,53,5,Ivan Azevedo,Camareira,Gov.,"""1.691,00""",2019-06-07
53,54,6,Natalia Campos,Analista Financeiro,Financeiro,"""5.601,00""",2022-12-26
54,55,6,Natalia Campos,MANUTENÇÃO,Manutenção,"""2.404,00""",2021-06-30

In [15]:
df_concatenado_funcionarios.iloc[9]

id_funcionario             10
id_unidade                  1
nome              Bruno Costa
cargo              Manutenção
departamento       Manutenção
salario               2314.00
data_admissao      2022-11-28
Name: 9, dtype: object

### Base Reservas

1) correção das diárias
2) correção da avaliação dos hóspedes
3) trata como nulo os campos "sem avaliação"

In [16]:
novos_valores = {
    728: 7, 955: 4, 1134: 3, 1152: 2, 
    1448: 6, 1581: 4, 2312: 4, 2384: 2,
}

novos_avaliacoes = {
    37: 1, 902: 1, 2073: 1, 933: 3, 1718: 3,
    2167: 3,
}

ids_valores = list(novos_valores.keys())
df_concatenado_reservas.loc[df_concatenado_reservas['id_reserva'].isin(ids_valores), 'qtd_diarias'] = df_concatenado_reservas['id_reserva'].map(novos_valores)

df_filtrado = df_concatenado_reservas[df_concatenado_reservas['id_reserva'].isin(ids_valores)]
display(df_filtrado)

,id_reserva,id_unidade,id_tipo_quarto,id_cliente,id_canal,data_checkin,data_checkout,qtd_diarias,num_hospedes,avaliacao_hospede,status_reserva,forma_pagamento
727,728,4,4,120,1.0,2023-09-22,2023-09-29,7,4,NaN,confirmada,Cartão de Crédito
954,955,7,3,211,2.0,2023-07-12,2023-07-16,4,1,9.0,confirmada,Dinheiro
1133,1134,5,1,125,4.0,2023-07-08,2023-07-11,3,2,2.0,cancelada,Transferência
1151,1152,5,2,59,4.0,2023-10-15,2023-10-17,2,1,3.0,CONFIRMADA,Transferência
1447,1448,8,3,52,1.0,2024-11-01,2024-11-07,6,3,8.0,confirmada,Dinheiro
1580,1581,10,3,280,2.0,2024-03-12,2024-03-16,4,3,10.0,concluída,Transferência
2311,2312,8,2,138,4.0,2024-08-25,2024-08-29,4,1,6.0,confirmada,Dinheiro
2383,2384,5,2,64,2.0,2024-10-01,2024-10-03,2,2,4.0,concluída,Dinheiro